source 'https://rubygems.org'

gem 'berkshelf', '~> 3.2'
gem 'chefspec', '~> 4.2'
gem 'foodcritic', '~> 4.0'
gem 'kitchen-gce', '= 0.2'
gem 'kitchen-vagrant', '~> 0.16'
gem 'rake', '~> 10.4'
gem 'rubocop', '~> 0.29'
gem 'stove', '~> 3.2', '>= 3.2.3'
gem 'test-kitchen', '~> 1.3', '>= 1.3.1'
gem 'thor-scmversion', '~> 1.7.0'
